CREATE TABLE TB_ESPECIALIDADE (
	ID SERIAL PRIMARY KEY,
	Nome VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE TB_MEDICO(
	ID SERIAL PRIMARY KEY,
	Nome VARCHAR(250),
	CRM VARCHAR(6) NOT NULL UNIQUE
);

CREATE TABLE TB_MEDICO_ESPECIALIDADE(
	ID SERIAL PRIMARY KEY,
	FK_MEDICO INTEGER,
	FOREIGN KEY (FK_MEDICO) REFERENCES TB_MEDICO (ID),
	FK_ESPECIALIDADE INTEGER,
	FOREIGN KEY (FK_ESPECIALIDADE) REFERENCES TB_ESPECIALIDADE (ID)
);

CREATE TABLE TB_PACIENTE(
	ID SERIAL PRIMARY KEY,
	Nome VARCHAR(250) NOT NULL,
	Data_Nascimeto DATE,
	CPF VARCHAR(11) NOT NULL UNIQUE,
	Sexo VARCHAR(1),
	Alergias VARCHAR(250),
	Medicamentos VARCHAR(250)
);

CREATE TABLE TB_CONSULTA(
	ID SERIAL PRIMARY KEY,
	FK_PACIENTE INTEGER,
	FOREIGN KEY (FK_PACIENTE) REFERENCES TB_PACIENTE (ID),
	FK_MEDICO_ESPECIALIDADE INTEGER,
	FOREIGN KEY (FK_MEDICO_ESPECIALIDADE) REFERENCES TB_MEDICO_ESPECIALIDADE (ID),
	DATA_HORA TIMESTAMP NOT NULL
);